import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/annotation-state.ts",
    "src/index.ts",
    "src/annotations.ts",
    "src/completion.ts",
    "src/context.ts",
    "src/constructs.ts",
    "src/dependency.ts",
    "src/dependency-metadata.ts",
    "src/dependency-runtime.ts",
    "src/displaywidth.ts",
    "src/doc.ts",
    "src/execution-context.ts",
    "src/extension.ts",
    "src/facade.ts",
    "src/fluent.ts",
    "src/input-trace.ts",
    "src/internal/annotations.ts",
    "src/internal/dependency.ts",
    "src/internal/parser.ts",
    "src/message.ts",
    "src/modifiers.ts",
    "src/nonempty.ts",
    "src/parser.ts",
    "src/phase2-seed.ts",
    "src/primitives.ts",
    "src/program.ts",
    "src/suggestion.ts",
    "src/usage.ts",
    "src/validate.ts",
    "src/valueparser.ts",
  ],
  dts: true,
  format: ["esm", "cjs"],
  unbundle: true,
  platform: "neutral",
});
