name: main

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
    - "*.*.*"
    branches:
    - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - uses: jdx/mise-action@v4
      with:
        experimental: true
        install: true
        log_level: ${{ runner.debug == '1' && 'debug' || 'info' }}
    - run: mise run check

  test-deno:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - run: sudo apt-get install -y zsh
    - uses: jdx/mise-action@v4
      with:
        experimental: true
        install: true
        log_level: ${{ runner.debug == '1' && 'debug' || 'info' }}
    - run: deno task test --coverage --junit-path=junit.xml
    - if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: junit.xml
        report_type: test_results
    - uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/lcov.info

  test-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - run: sudo apt-get install -y zsh
    - uses: jdx/mise-action@v4
      with:
        experimental: true
        install: true
        log_level: ${{ runner.debug == '1' && 'debug' || 'info' }}
    - run: mise run test:node

  test-bun:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - run: sudo apt-get install -y zsh
    - uses: jdx/mise-action@v4
      with:
        experimental: true
        install: true
        log_level: ${{ runner.debug == '1' && 'debug' || 'info' }}
    - run: mise run test:bun

  publish:
    if: github.event_name == 'push'
    needs: [test-node, test-deno, test-bun, check]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v6
    - uses: jdx/mise-action@v4
      with:
        experimental: true
        install: true
        log_level: ${{ runner.debug == '1' && 'debug' || 'info' }}
    - run: |
        set -ex
        if [[ "$GITHUB_REF_TYPE" == tag ]]; then
        mise run check:versions
          [[ "$(jq -r '.version' packages/core/deno.json)" == "$GITHUB_REF_NAME" ]]
        else
          jq \
            --arg build "$GITHUB_RUN_NUMBER" \
            --arg commit "${GITHUB_SHA::8}" \
            '.version = .version + "-dev." + $build + "+" + $commit' \
            packages/core/deno.json > /tmp/deno.json
          mv /tmp/deno.json packages/core/deno.json
          mise run check:versions --fix
        fi
    - run: |
        set -ex
        # jsr.io is flaky these days; deno publish often hangs until it
        # times out, but eventually succeeds after enough retries.
        for attempt in $(seq 1 30); do
          if timeout 60 deno publish --allow-dirty; then
            break
          elif [[ "$attempt" -eq 30 ]]; then
            echo "deno publish failed after $attempt attempts." >&2
            exit 1
          else
            echo "deno publish failed (attempt $attempt); retrying..." >&2
            sleep 10
          fi
        done
        if [[ "$GITHUB_REF_TYPE" == tag ]]; then
          pnpm publish \
            --recursive \
            --no-git-checks \
            --access public \
            --force
        else
          pnpm publish \
            --recursive \
            --no-git-checks \
            --access public \
            --force \
            --tag dev
        fi
      env:
        NPM_CONFIG_PROVENANCE: "true"

  public-docs:
    if: github.event_name == 'push'
    needs: [publish]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      deployments: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v6
    - uses: jdx/mise-action@v4
      with:
        experimental: true
        install: true
        log_level: ${{ runner.debug == '1' && 'debug' || 'info' }}
    - run: |
        set -ex
        if [[ "$GITHUB_REF_TYPE" = "tag" ]]; then
          EXTRA_NAV_TEXT=Unstable \
          EXTRA_NAV_LINK="$UNSTABLE_DOCS_URL" \
          SITEMAP_HOSTNAME="$STABLE_DOCS_URL" \
          JSR_REF_VERSION=stable \
          pnpm build
        else
          EXTRA_NAV_TEXT=Stable \
          EXTRA_NAV_LINK="$STABLE_DOCS_URL" \
          SITEMAP_HOSTNAME="$UNSTABLE_DOCS_URL" \
          JSR_REF_VERSION=unstable \
          pnpm build
        fi
      env:
        STABLE_DOCS_URL: ${{ vars.STABLE_DOCS_URL }}
        UNSTABLE_DOCS_URL: ${{ vars.UNSTABLE_DOCS_URL }}
        SITEMAP_HOSTNAME: ${{ vars.SITEMAP_HOSTNAME }}
        PLAUSIBLE_DOMAIN: ${{ vars.PLAUSIBLE_DOMAIN }}
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
      working-directory: docs
    - uses: actions/upload-pages-artifact@v5
      with:
        path: docs/.vitepress/dist
    - id: deployment
      if: github.ref_type == 'tag'
      uses: actions/deploy-pages@v5
    - if: github.ref_type == 'branch'
      uses: cloudflare/wrangler-action@v4
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        gitHubToken: ${{ github.token }}
        command: >-
          pages deploy .vitepress/dist
          --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }}
        packageManager: pnpm
        workingDirectory: ${{ github.workspace }}/docs/

# cSpell: ignore dpkg keyrings dearmor denoland npmjs vitepress
